#functions_d.py

import numpy as np
import pandas as pd
import scipy.special as special
from numba import jit
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['text.usetex'] = True
from matplotlib.transforms import (
    Bbox, TransformedBbox, blended_transform_factory)
# Import math Library
import math 

from sympy import *

# PARA USAR A LA HORA DE GUARDAR DOS COLUMNAS EN UN ARCHIVO
import csv

import cmath
np.seterr(divide='ignore', invalid='ignore')

class Panel:
    def __init__(self,d=1,sigma=1.0,epsilon= 0.5 ,vp=0.0001):
        self.d = d
        self.sigma = sigma
        self.vp=  vp
        self.epsilon = epsilon 
        self.eta0 = (2+self.d)*np.sqrt(np.pi/2)/8
        self.kapa0= (2+self.d)*self.eta0/2
    def a2d(self,alpha):
            return  16*(1-2*alpha**2.00)*(1-alpha)/(9+24*self.d+(8*self.d-41)*alpha+30*alpha**2.00*(1-alpha))
            
    def zet(self, alpha):
            return ( (2 + self.d) / (4*self.d) )*( 1 - alpha**2.00 )*( 1+3*self.a2d(alpha) / 16 ) 
    
    def nu1(self, alpha):
            return (3-3*alpha+2*self.d)*(1+alpha)*(1-self.a2d(alpha)/32)/(4*self.d)
    def nu2(self,alpha):
            return (1+alpha)*((self.d-1)/2+3*(self.d+8)*(1-alpha)/16+(4+5*self.d-3*(4-self.d)*alpha)*self.a2d(alpha)/512)    
    
    def eta(self,alpha):
                return 1 / ( self.nu1(alpha)- self.zet(alpha) * 0.5)       
    def kapa(self,alpha):
        return (1+2*self.a2d(alpha))*(self.d-1)/(self.nu2(alpha)-2*self.d*self.zet(alpha))
    def kapa1d(self,alpha):
        return (1+2*self.a2d(alpha))/(self.nu2(alpha)-2*self.d*self.zet(alpha))
    def mu(self,alpha):
        return 2*self.zet(alpha)* (self.kapa(alpha)+(self.d-1)*self.a2d(alpha)/(self.d*self.zet(alpha)))/(2*self.nu2(alpha)/self.d-3*self.zet(alpha))
    
    def mu1d(self,alpha):
        return 2*self.zet(alpha)* (self.kapa1d(alpha)+self.a2d(alpha)/(self.d*self.zet(alpha)))/(2*self.nu2(alpha)/self.d-3*self.zet(alpha))
    def sol1(self,k,alpha):  
            return    -(-3*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) + 
                            self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) - self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 
                            2*self.d**2*k**2 - 2*self.d**2*self.zet(alpha)**2 - 4*self.d*self.eta(alpha)*k**2*self.zet(alpha) + 
                            self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 
                            2*self.d*self.zet(alpha)**2 + 2*self.eta(alpha)*k**2*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) - 4*k**2)/(2*self.d**2 - 2*self.d) +
                            (2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 
                            2*self.eta(alpha)*k**2+0j)**2/(2*self.d**2 - 2*self.d+0j)**2)/(3*(np.sqrt(-4*(-3*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) + self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) - 
                            self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d**2*k**2 - 2*self.d**2*self.zet(alpha)**2 - 4*self.d*self.eta(alpha)*k**2*self.zet(alpha) +
                            self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 2*self.d*self.zet(alpha)**2 + 2*self.eta(alpha)*k**2*self.zet(alpha) -
                            2*k**4*self.kapa(alpha)*self.zet(alpha) - 4*k**2)/(2*self.d**2 - 2*self.d) + (2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 +
                            2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2+0j)**2/(2*self.d**2 - 2*self.d+0j)**2+0j)**3 + (-9*(2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 
                            4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) +
                            self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) - self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d**2*k**2 - 2*self.d**2*self.zet(alpha)**2 - 
                            4*self.d*self.eta(alpha)*k**2*self.zet(alpha) + self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 2*self.d*self.zet(alpha)**2 + 
                            2*self.eta(alpha)*k**2*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) - 4*k**2)/(2*self.d**2 - 2*self.d)**2 + 2*(2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 
                                                                                                                                           4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)**3/(2*self.d**2 - 
                                                                                                                                                                                                                                  2*self.d)**3 + 27*(self.d*k**4*self.kapa(alpha) - self.d*k**4*self.mu(alpha) - 
                                                                                                                                                                                                                                                     2*self.d*k**2*self.zet(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) + 
                                                                                                                                                                                                                                                     2*k**2*self.zet(alpha))/(2*self.d - 2)+0j)**2+0j)/2 - 9*(2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) + self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) - self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d**2*k**2 - 2*self.d**2*self.zet(alpha)**2 - 4*self.d*self.eta(alpha)*k**2*self.zet(alpha) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                           self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 2*self.d*self.zet(alpha)**2 + 2*self.eta(alpha)*k**2*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) - 4*k**2)/(2*(2*self.d**2 - 2*self.d)**2) + (2*self.d**2*self.eta(alpha)*k**2 + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)**3/(2*self.d**2 - 2*self.d)**3 + 27*(self.d*k**4*self.kapa(alpha) - self.d*k**4*self.mu(alpha) - 2*self.d*k**2*self.zet(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) + 2*k**2*self.zet(alpha))/(2*(2*self.d - 2))+0j)**(1/3)) - (np.sqrt(-4*(-3*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) + self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) - self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d**2*k**2 -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2*self.d**2*self.zet(alpha)**2 - 4*self.d*self.eta(alpha)*k**2*self.zet(alpha) + self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 2*self.d*self.zet(alpha)**2 + 2*self.eta(alpha)*k**2*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4*k**2)/(2*self.d**2 - 2*self.d) + (2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)**2/(2*self.d**2 - 2*self.d)**2)**3 + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      (-9*(2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) + self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d**2*k**2 - 2*self.d**2*self.zet(alpha)**2 - 4*self.d*self.eta(alpha)*k**2*self.zet(alpha) + self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 2*self.d*self.zet(alpha)**2 + 2*self.eta(alpha)*k**2*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) - 4*k**2)/(2*self.d**2 - 2*self.d)**2 + 2*(2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)**3/(2*self.d**2 - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2*self.d)**3 + 27*(self.d*k**4*self.kapa(alpha) - self.d*k**4*self.mu(alpha) - 2*self.d*k**2*self.zet(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) + 2*k**2*self.zet(alpha))/(2*self.d - 2)+0j)**2+0j)/2 - 9*(2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   2*self.eta(alpha)*k**2)*(2*self.d**2*self.eta(alpha)*k**2*self.zet(alpha) + self.d**2*k**4*self.kapa(alpha)*self.zet(alpha) - self.d**2*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d**2*k**2 - 2*self.d**2*self.zet(alpha)**2 - 4*self.d*self.eta(alpha)*k**2*self.zet(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          self.d*k**4*self.kapa(alpha)*self.zet(alpha) - 2*self.d*k**2*self.kapa(alpha)*self.zet(alpha) + 2*self.d*k**2 + 2*self.d*self.zet(alpha)**2 + 2*self.eta(alpha)*k**2*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) - 4*k**2)/(2*(2*self.d**2 - 2*self.d)**2) + (2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2+0j)**3/(2*self.d**2 - 2*self.d)**3 + 27*(self.d*k**4*self.kapa(alpha) - self.d*k**4*self.mu(alpha) - 2*self.d*k**2*self.zet(alpha) + 2*k**4*self.kapa(alpha) -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2*k**4*self.mu(alpha) + 2*k**2*self.zet(alpha))/(2*(2*self.d - 2))+0j)**(1/3)/3 - (2*self.d**2*self.eta(alpha)*k**2 + self.d**2*k**2*self.kapa(alpha) - 4*self.d*self.eta(alpha)*k**2 + 2*self.d*k**2*self.kapa(alpha) + 2*self.eta(alpha)*k**2)/(3*(2*self.d**2 - 2*self.d))
        
    def sol2(self,k,alpha):  
            return    -(-3*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 
                            2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 
                            2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 
                            2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d) + 
                        (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) +
                         2*k**2*self.eta(alpha))**2/(2*self.d**2 - 2*self.d)**2)/(3*(-1/2 - np.sqrt(3)*1j/2)*(np.sqrt(-4*(-3*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + 
                                                                                                                       k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) +
                                                                                                                       2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) +
                                                                                                                       2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 
                                                                                                                       2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d) + 
                                                                                                                       (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) +
                                                                                                                        2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**2/(2*self.d**2 - 2*self.d)**2)**3 + 
                                                                                                                   (-9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) +
                                                                                                                        2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) -
                                                                                                                                                 k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d)**2 + 2*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 
                                                                                                                                                                                                                                                         2*k**2*self.eta(alpha))**3/(2*self.d**2 - 2*self.d)**3 + 27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) -
                                                                                                                                                                                                                                                                                                                      2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*self.d - 2)+0j)**2+0j)/2 - 
                                                                                                              9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 
                                                                                                                                                                                                                                                                                2*self.d*self.zet(alpha)**2)/(2*(2*self.d**2 - 2*self.d)**2) + (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**3/(2*self.d**2 - 2*self.d)**3 + 
                                                                                                              27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*(2*self.d - 2))+0j)**(1/3)) - (-1/2 - np.sqrt(3)*1j/2)*(np.sqrt(-4*(-3*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                         k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d) + 
                                                                                                                                                                                                                                                                                                                                                     (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**2/(2*self.d**2 - 2*self.d)**2)**3 + (-9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d)**2 + 2*(2*k**2*self.d**2*self.eta(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**3/(2*self.d**2 - 2*self.d)**3 + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*self.d - 2)+0j)**2+0j)/2 - 9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*(2*self.d**2 - 2*self.d)**2) + (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha)+0j)**3/(2*self.d**2 - 2*self.d+0j)**3 +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*(2*self.d - 2))+0j)**(1/3)/3 - (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))/(3*(2*self.d**2 - 2*self.d))
    def sol3(self,k,alpha):
        return -(-3*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - 
                     k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d) + 
                 (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha)+0j)**2/(2*self.d**2 - 2*self.d+0j)**2)/(3*(-1/2 + np.sqrt(3)*1j/2)*(np.sqrt(-4*(-3*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**2/(2*self.d**2 - 2*self.d)**2)**3 + 
                                                                                                                                                                                                                                              (-9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) -
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d)**2 + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            2*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**3/(2*self.d**2 - 2*self.d)**3 + 27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*self.d - 2) +0j)**2+0j)/2 - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*(2*self.d**2 - 2*self.d)**2) +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**3/(2*self.d**2 - 2*self.d)**3 + 27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*(2*self.d - 2))+0j)**(1/3)) - (-1/2 + np.sqrt(3)*1j/2)*(np.sqrt(-4*(-3*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**2/(2*self.d**2 - 2*self.d)**2)**3 + (-9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*self.d**2 - 2*self.d)**2 + 2*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))**3/(2*self.d**2 - 2*self.d)**3 + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*self.d - 2))**2+0j)/2 - 9*(2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))*(k**4*self.d**2*self.kapa(alpha)*self.zet(alpha) + k**4*self.d*self.kapa(alpha)*self.zet(alpha) - 2*k**4*self.kapa(alpha)*self.zet(alpha) + 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2*k**2*self.d**2*self.eta(alpha)*self.zet(alpha) - k**2*self.d**2*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d**2 - 4*k**2*self.d*self.eta(alpha)*self.zet(alpha) - 2*k**2*self.d*self.kapa(alpha)*self.zet(alpha) + 2*k**2*self.d + 2*k**2*self.eta(alpha)*self.zet(alpha) - 4*k**2 - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    2*self.d**2*self.zet(alpha)**2 + 2*self.d*self.zet(alpha)**2)/(2*(2*self.d**2 - 2*self.d)**2) + (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha)+0j)**3/(2*self.d**2 - 2*self.d)**3 + 27*(k**4*self.d*self.kapa(alpha) - k**4*self.d*self.mu(alpha) + 2*k**4*self.kapa(alpha) - 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        2*k**4*self.mu(alpha) - 2*k**2*self.d*self.zet(alpha) + 2*k**2*self.zet(alpha))/(2*(2*self.d - 2))+0j)**(1/3)/3 - (2*k**2*self.d**2*self.eta(alpha) + k**2*self.d**2*self.kapa(alpha) - 4*k**2*self.d*self.eta(alpha) + 2*k**2*self.d*self.kapa(alpha) + 2*k**2*self.eta(alpha))/(3*(2*self.d**2 - 2*self.d))    
    def sol_t(self,k,alpha):
        return self.zet(alpha) - 0.5*self.eta(alpha)*k**2  
    
    def sol11d(self,k,alpha):
        return -k**2*self.kapa1d(alpha)/2 - (9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2)/(3*(27*k**6*self.kapa1d(alpha)**3/8 + 81*k**4*self.kapa1d(alpha)/4 - 81*k**4*self.mu1d(alpha)/4 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/4 - 27*k**2*self.zet(alpha)/2 + np.sqrt(-4*(9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2+0j)**3 + (27*k**6*self.kapa1d(alpha)**3/4 + 81*k**4*self.kapa1d(alpha)/2 - 81*k**4*self.mu1d(alpha)/2 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/2 - 27*k**2*self.zet(alpha)+0j)**2+0j)/2+0j)**(1/3)) - (27*k**6*self.kapa1d(alpha)**3/8 + 81*k**4*self.kapa1d(alpha)/4 - 81*k**4*self.mu1d(alpha)/4 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/4 - 27*k**2*self.zet(alpha)/2 + np.sqrt(-4*(9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2+0j)**3 + (27*k**6*self.kapa1d(alpha)**3/4 + 81*k**4*self.kapa1d(alpha)/2 - 81*k**4*self.mu1d(alpha)/2 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/2 - 27*k**2*self.zet(alpha)+0j)**2+0j)/2+0j)**(1/3)/3
    def sol21d(self,k,alpha):
        return     -k**2*self.kapa1d(alpha)/2 - (9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2)/(3*(-1/2 - np.sqrt(3)*1j/2)*(27*k**6*self.kapa1d(alpha)**3/8 + 81*k**4*self.kapa1d(alpha)/4 - 81*k**4*self.mu1d(alpha)/4 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/4 - 27*k**2*self.zet(alpha)/2 + np.sqrt(-4*(9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2+0j)**3 + (27*k**6*self.kapa1d(alpha)**3/4 + 81*k**4*self.kapa1d(alpha)/2 - 81*k**4*self.mu1d(alpha)/2 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/2 - 27*k**2*self.zet(alpha)+0j)**2+0j)/2+0j)**(1/3)) - (-1/2 - np.sqrt(3)*1j/2)*(27*k**6*self.kapa1d(alpha)**3/8 + 81*k**4*self.kapa1d(alpha)/4 - 81*k**4*self.mu1d(alpha)/4 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/4 - 27*k**2*self.zet(alpha)/2 + np.sqrt(-4*(9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2+0j)**3 + (27*k**6*self.kapa1d(alpha)**3/4 + 81*k**4*self.kapa1d(alpha)/2 - 81*k**4*self.mu1d(alpha)/2 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/2 - 27*k**2*self.zet(alpha)+0j)**2+0j)/2+0j)**(1/3)/3
    def sol31d(self,k,alpha):
        return  -k**2*self.kapa1d(alpha)/2 - (9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2)/(3*(-1/2 + np.sqrt(3)*1j/2)*(27*k**6*self.kapa1d(alpha)**3/8 + 81*k**4*self.kapa1d(alpha)/4 - 81*k**4*self.mu1d(alpha)/4 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/4 - 27*k**2*self.zet(alpha)/2 + np.sqrt(-4*(9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2+0j)**3 + (27*k**6*self.kapa1d(alpha)**3/4 + 81*k**4*self.kapa1d(alpha)/2 - 81*k**4*self.mu1d(alpha)/2 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/2 - 27*k**2*self.zet(alpha))**2+0j)/2+0j)**(1/3)) - (-1/2 + np.sqrt(3)*1j/2)*(27*k**6*self.kapa1d(alpha)**3/8 + 81*k**4*self.kapa1d(alpha)/4 - 81*k**4*self.mu1d(alpha)/4 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/4 - 27*k**2*self.zet(alpha)/2 + np.sqrt(-4*(9*k**4*self.kapa1d(alpha)**2/4 - 9*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 + 9*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 - 9*k**2 + 3*self.zet(alpha)**2+0j)**3 + (27*k**6*self.kapa1d(alpha)**3/4 + 81*k**4*self.kapa1d(alpha)/2 - 81*k**4*self.mu1d(alpha)/2 - 27*k**2*self.kapa1d(alpha)*(3*k**4*self.kapa1d(alpha)*self.zet(alpha)/2 - 3*k**2*self.kapa1d(alpha)*self.zet(alpha)/2 + 3*k**2 - self.zet(alpha)**2)/2 - 27*k**2*self.zet(alpha)+0j)**2+0j)/2+0j)**(1/3)/3
    def kc(self,alpha):
            return np.sqrt(2*(self.d-1)*self.zet(alpha)/((self.d+2)*(self.kapa(alpha)-self.mu(alpha))))
    def kc1d(self,alpha):
            return np.sqrt(2*self.zet(alpha)/((self.d+2)*(self.kapa1d(alpha)-self.mu1d(alpha))))
 
